name: Build and Deploy Logic App
on:   
  workflow_dispatch

env:
  name: 'logicapp29'
  rg-name: 'rg-logic-app'

jobs:
  logic-app-build:
    name: Build
    runs-on: ubuntu-latest  
    # environment: ${{inputs.EnvironmentsToDeploy}}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Package Logic app
      run: (cd logicapps; mkdir -p ../output; zip -r ../output/logic.zip . -x .\* -x ".gitignore" -x "README")
    - name: Upload app zip package
      uses: actions/upload-artifact@v4
      with:
       name: logic
       path: ./output/
       retention-days: 1

  logic-app-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [logic-app-build]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_SECRET_MURALI}}
        enable-AzPSSession: true
    - uses: actions/download-artifact@v4
      with:
        name: logic

    

    - name: Get Publish Profile
      id: publishprofile
      uses: azure/powershell@v1
      with:
        inlineScript: |
         $profile = Get-AzWebAppPublishingProfile `
         -ResourceGroupName ${{env.rg-name}} `
         -Name ${{env.name}}
         $profile = $profile.Replace("`r","").Replace("`n","")
         Write-Output "::set-output name=profile::$profile"
        azPSVersion: latest

    - name: Deploy to Azure Logic App
      uses: azure/functions-action@v1.3.1
      id: la
      with:
         app-name: ${{env.name}}
         package: './logic.zip'
         publish-profile: ${{steps.publishprofile.outputs.profile}}
        # publish-profile: ${{secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE}}
         
     
        
      
    
       
    
    
